# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#
# Should more or less follow lint and typing settings as found is tox.ini
#
# Once pre-commit package is installed in your environnement, install hooks
# with `pre-commit install`
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: trailing-whitespace
    exclude: 'lowatt_enedis/wsdl'
  - id: end-of-file-fixer
    exclude: 'lowatt_enedis/wsdl'
  - id: check-added-large-files
- repo: local
  hooks:
  - id: ruff-check
    name: ruff-check
    entry: ruff check
    language: system
    types: [python]
  - id: ruff-format
    name: ruff
    entry: ruff format --check --diff
    language: system
    types: [python]
